version: "3.8"

services:
  frontend-dev:
    image: node:20.19-alpine   # Dùng Node 20
    working_dir: /app
    volumes:
      - ./:/app:delegated       # Mount source code vào container
      - /app/node_modules       # Giữ node_modules bên trong container
    ports:
      - "5173:5173"
    environment:
      CHOKIDAR_USEPOLLING: "true"
    command: sh -c "npm install --silent && npm run dev -- --host 0.0.0.0"
